# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network requests to Google Analytics when you use CocoaPods.
# We recommend that you opt-out for privacy reasons.
# To opt-out, run `pod repo-art update` and then `pod repo-art add` to add the Artsy repo.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig not found. To fix, run \"flutter build ios\" or \"flutter run\"."
  end

  File.read(generated_xcode_build_settings_path).each_line do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in Generated.xcconfig. To fix, run \"flutter build ios\" or \"flutter run\"."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
